# Generated by Django 5.2.3 on 2025-06-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='query',
            new_name='parameters',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='suggestion',
            new_name='recommended_products',
        ),
    ]
